export const fontSizes = {
  a_extraSmall: "6px",
  b_tiny: "8px",
  c_smallCaption: "9px",
  d_caption: "10px",
  e_smallSubtitle: "11px",
  f_subtitle: "12px",
  g_smallNormal: "13px",
  h_normal: "14px",
  i_largeNormal: "15px",
  j_title: "16px",
  k_largeTitle: "17px",
  l_highlight: "18px",
  m_subheading: "19px",
  n_heading: "20px",
  o_largeHeading: "22px",
  p_extraLargeHeading: "24px",
  q_smallDisplay: "26px",
  r_display: "28px",
  s_largeDisplay: "32px",
  t_extraLargeDisplay: "36px",
  u_jumboDisplay: "38px",
  v_superDisplay: "40px",
};
export type FontSizesType = typeof fontSizes;
